module.exports = [
  "My first dog (and best friend) was Barkley, a sweet, playful cairn terrier that was already a few years old by the time I was born. I’m assuming one of my brothers is at fault for this weird logic, but I grew up viewing Barkley as my equal in the family. I would never pick him up, because I would think to myself, I can’t. Barkley is older than I am. We went on like that for 13 years.",
  "When I was 5 we brought my first dog, a gorgeous, burnt sienna golden retriever, back from the Humane Society. She was sweet and gregarious, but we were worried that she was deaf or kind of stupid because she wouldn’t respond to the name they gave us at her shelter, Misty. ‘Misty!’ we kept yelling. ‘Misty!’ Later that night, my mother looked in the paperwork they had given us. ‘It says her name is Tawny?’ The dog came running, smiling ear to ear, and we never mentioned ‘Misty’ again.",
  "My family had a dog and two cats when I was born (winners, all!) but the first authentically NEW pet in my life was an Airedale terrier puppy named Punto. On the day we went to pick him up, we knew which one he was because this ribbon around his neck was purple, a noble color. He was very small and curly, and peed on my mom’s lap on the way home, which we all optimistically interpreted as an expression of his deep sense of comfort and belonging. We named him in honor of a previous fox terrier my mom had as a kid (Punto is a Norwegian name, I think?). He grew up to be fairly large and unfailingly sweet. He was once tied by his leash to the leg a garden chair, at some point tried to get up and run after a tennis ball or something, and was TERRIFIED to find that the chair was CHASING HIM. From that point on, he was always nervous around furniture, thunderstorms, and arguments. I loved him with all my heart.",
  "My first pet, a golden retriever my parents named Yeti, met for the first time when I came home from the hospital at 3 days old. He was the best, most gentle and patient dog I’ve ever met. He put up with me and my brother in our toddler years, and perhaps because of that, he never really saw us as humans he had to listen to. I can’t remember anything about my early years that doesn’t include Yeti.",
  "When I was a junior in college, I decided it was time for my very own pup. My friend Rachel and I had been on the lookout for what felt like months — we literally went through every local site and newspaper ad until I almost gave up hope. One day she came across a listing for puppies at a house 30 miles away. We called and the man said he had one dog left. When we got there, we followed him into his living room until we saw a camouflage baby pen. Sitting in the middle was the tiniest, most adorable dog I had ever seen. I picked him up, and that was that. We drove him home and named him Jean-Pierre.",
  "My first real pet (sorry to the cat I had until I was 6) was a dog, Kelsey, who we got when I was in third grade. She was the runt of the litter and has a slightly crooked tail because, we think, she was squished around inside her mama’s belly. Anyway, we got her the day of the Oscars, or some award show, and I remember bringing her into the family room to watch. At some point, she accidentally peed on my brother. That is when I knew I would love her forever.",
  "My family had two dogs, two bunnies, two birds, and probably some hamsters when I was born, but the first pet whom I felt was mine was Cosmo. I met him after soccer practice when I was 4. Someone had a litter of puppies in the back of their car and I sat amongst them and picked the one who fell asleep in my lap (I use this same technique for picking dogs now). I wanted to name him Rachael, after my best friend, but my mom said I had to give him a boy’s name, so I named him after my rat-tailed wielding pre-school crush, Cosmo. He was the absolute best: He would play hide-and-seek with me (to this day, I have no idea how it workedm but I know we played it) and lived a great life running throughout the canyon we lived in. We called him the bionic dog because he survived getting hit by a car, shot with a BB gun (awful neighborhood kid), and bitten by a rattlesnake with barely a scratch remaining.",
  "Bo wasn’t my family’s first pet, but he was my first pet. I was 19 and my mother and I had gone to the local animal shelter to donate some food and cleaning supplies. I went to go look at dogs ‘just to see them,’ and each dog I walked past ran to the front of their cages to say hello. At the very end of the row I didn’t see any dog, so I assumed it was empty. When I got there, however, a rather large and fluffy dog was lying in the back of the cage. He didn’t get up — just looked up at me and thumped his tail a few times. I look at the information on his cage door, and there was a sign on it that said, ‘I’ve been here a long time and my time is almost up.’ It had the next day’s date on it. This dog was on borrowed time. I knelt down, and he stood up, tail held low but wagging, and approached me and licked my fingers through the chain link. When I asked the shelter attendant if I could walk him.",
  "My parents and I had just moved out of my grandma’s apartment building, and we were visiting her when we heard tiny kitten screams from the backyard one night. Lo and behold, this friendly little tabby was sitting in the middle of a concrete square, all by herself, staring up at the window and meowing. Obviously we took her in and she became our cat because OMG stray kitten! We had also just found another cat, who became her boyfriend, Nicky (named after Knickerbocker, the street where we found HIM). They had a litter of kittens together and she became a surprise ‘teen mom’ before we were able to spay her. Nicky got really sick and didn’t last too long, sadly.",
]
