module.exports = [
  "Dishonored 2 is about taking systematic revenge on a conspiracy of nobles (again), but the real fun is in all the systemic shenanigans you can pull off along the way. Play for a few minutes and you won't notice much difference from the original game, aside from graphics that elevate their stylized figures into nigh-photorealistic grotesques. Play for an hour or two and you'll see how all of the little improvements to the familiar model add up: lob a bottle of cider at a guard",
  "Doom isn't just the best pure FPS of the year - or in fact a good many years before this one. It isn't just a blisteringly kinetic, deeply intelligent, hilariously self-aware cavalcade of strategic slaughter, running on a hot engine of pure, player agency and drenched with lightly steaming adrenaline. If it was just those things, Doom would still be the number two game on this list. Its immediate, accessible, but immensely layered action is just that damn good. But Doom does more than that. Doom knows it has the finest-crafted distillation of FPS values around, and so it sets out to explode, explore, examine and expand those systems in every possible permutation and reinterpretation, to create the greatest celebration (and evolution) of FPS imaginable. Doom knows why the genre was important in the first place, and so it dedicates",
  "Who knew? Our actual Game of the Year is a big, dumb shooter about a space-dude and his space-dude robot. Well, actually, that's a gross reduction of Titanfall 2. For starters there's nothing dumb about the core shooting here, which is slick and quick as anything you've played this generation. Being able to triple wall-run down a corridor, while lobbing a grenade at a bunch of enemies and headshotting another, before touching down, knee-sliding under a low-beam, shotgunning another couple of baddos, then leaping into your titan is… look, it just feels really, really good. When you're flowing through Titanfall 2 and you start to chain together your moves it's an incredible s",
  "Unforgiving. Brutal. Sadistic. All apt words to describe Dark Souls 3, but here's three more: completely worth it. Ruined cities and marshy forests surround you as you make your way deeper into the fiendishly challenging world of Dark Souls, and despite the fact the narrative takes a back seat, if you take the time to look around you can piece together what went on before the world became a monstrous hive of activity. Each enemy is distinct from the one that came before both in looks and attacks, so combat ne",
  "It's fair to say that Final Fantasy 15 is, at the best of times, a wee bit wonky. The story is practically unintelligible unless you've see companion movie Kingsglaive, the back half is an odd shift in gameplay, and there are bugs aplenty. And yet this is perhaps the most recognizable, relatable Final Fantasy yet. Noctis and his three companions are chatting with gods, fighting magical robots, and renting horse-sized chickens, true, but they're also doing what friends do - comforting each other in a time of ",
  "While other FPS games turned to increasingly futuristic settings and gameplay, Battlefield developer DICE looked to the past for inspiration on this year's entry. The result, ironically enough, is one of the freshest feeling shooters in years. The campaign, while short, is drop-dead gorgeous, with some heartfelt drama interspersed with bombastic set pieces like zeppelins hovering over London. Then you enter the fray ",
  "There is much to love and praise about Overwatch that you could say about any well-crafted shooter. You get well-executed gunplay, unique character classes, exciting maps, and a variety of game modes. But two things make Overwatch special. First are the unexpected moments. Maybe it's when Genji deflects a McCree ultimate back in the cowboy's face, saving the day. Or it's when all twelve players pick Mercy and have an impromptu dance party. Those are the immediately-YouTubed plays that make you howl with laughter because you've just experienced something totally unique with this group of twelve players. And that's the second part of Overwatch's ",
  "Hitman is every bit of raw potential from the 16-year-old series, delivered in just the right way to emphasize its strengths and minimize weaknesses. Hitman: Blood Money and the Contracts mode from Hitman: Absolution made it clear that 47 is at his best when he has big levels full of people and endless, inventive ways to kill them. But making intricate puzzle boxes like that takes time, and players can't fully app"
]
